# fly.toml app configuration file generated for suc on 2023-11-08T11:09:06-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "suc"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "41641"

[[services]]
  protocol = "udp"
  internal_port = 41641
  processes = ["app"]

  [[services.ports]]
    port = 41641
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 75
